### ISSUE TITLE
[Bug] Window Blocks not culling correctly

### ISSUE THREAD

**Issue by NonplussedUltra** [copycats-plus/copycats#128]
**Describe the bug**
When using `copycats:copycat_block` with Create windows, the north/south/east/west faces connect as they should, but the top/bottom faces' wood plank texture is visible at boundaries between the two block types.

**To Reproduce**
1. Place a Create window.
2. Place a `copycats:copycat_block` on top of it, and assign it the same texture as the Create window.
3. Next to these, stack two Create window blocks.
4. Inside the assembly of two Create windows, no boundary is visible. Between the copycat and the Create window, the wood planks face is visible inside.

**Expected behavior**
Expected that the copycat and the Create window textures would connect seamlessly.

**Screenshots**
![2024-07-27_22 53 47](https://github.com/user-attachments/assets/4c3396b2-53d7-412e-b536-6c65f2461935)

**Desktop (please complete the following information):**
 - Minecraft 1.20.1
 - Forge 47.2.0
 - Copycats+ 2.0.5

**Additional context**
Also running Embeddium.

**Comment by Bennyboy1695** [comment]
Its very likely the window blocks from create are doing something special to work the way they do. I expect we need to add support for them properly to function how they should.
Thanks for the report

**Comment by hlysine** [comment]
Face hiding only works between 2 copycats, not between a copycat and a normal block. This isn't something specific to windows, since most blocks implement simple face hiding with the `skipRendering` method, which doesn't provide enough info for copycats to decide whether their shapes match. If you have two copycats next to each other, Forge uses the `hidesNeighborFace` method to allow shape comparison, while Fabric just works its magic to hide faces automatically.
