### ISSUE TITLE
crash Minecraft on 1.18.2[Bug] 

### ISSUE THREAD

**Issue by givic** [copycats-plus/copycats#139]
**Describe the bug**
if i enable copycats of the newest version of minecraft crashes. if i don't add it crashes. if i put the oldest it works. 

**To Reproduce**
1. Go to 'launcher'
2. Click on '"start to play"'
3. See error

**Screenshots**
![image](https://github.com/user-attachments/assets/7d3557ea-af17-477c-9bcf-005e57246ea0)
![image](https://github.com/user-attachments/assets/d5ab6943-b73c-4e95-a547-a2cd1bde0276)

**Desktop (please complete the following information):**
 - Minecraft Version: [1.18.2]
 - Mod Loader[Forge]
 - Mod Version [2.1.2]

**Additional context**
in general I don't know if I should write here because in the log file the mod is not involved in any way (I didn't find it) but it is with it that everything either works or doesn't work... so I hope for help

**Comment by hlysine** [comment]
Please post your crash report. There is nothing we can do to help if your issue isn't related to Copycats+

**Comment by givic** [comment]
Oh, yeah. I apologize for not thinking of that right away...
[crash-2024-08-04_16.44.00-fml.txt](https://github.com/user-attachments/files/16487582/crash-2024-08-04_16.44.00-fml.txt)

**Comment by hlysine** [comment]
That looks weird. Can you remove Copycats+ and send another crash report?

**Comment by givic** [comment]
Yes, of course I can. (could you explain a little bit what strange means? I tried to fix it myself but my skills were obviously not enough so it would be nice to know what the problem was).
[crash-2024-08-04_16.57.23-fml.txt](https://github.com/user-attachments/files/16487608/crash-2024-08-04_16.57.23-fml.txt)

**Comment by hlysine** [comment]
You still have Copycats+ installed according to the crash report.

It is strange because the crash report says that a piece of code from older versions of Copycats+ is missing, which likely means another mod is relying on it to function, although I'm not aware of any mods that have Copycats+ as a required dependency.

**Comment by givic** [comment]
geez... I'm really stupid. I didn't delete copycats, I deleted his addon..... (it must be sad for you to see idiots like me... sorry...) this report does not have copycats addons and copycats itself.  
[crash-2024-08-04_17.17.29-fml.txt](https://github.com/user-attachments/files/16487659/crash-2024-08-04_17.17.29-fml.txt)

**Comment by hlysine** [comment]
No need to feel sorry for that 😄 It is hard to manage so many mods. 

The same error appears when Copycats+ is removed, so another mod certainly depends on old Copycats+ code to function. Can you try to remove Create: Connected just to make sure it's not the Connected/Copycats+ compat that's causing the issue? (Make sure to back up your world since blocks are going to disappear if the game doesn't crash) If that doesn't solve the issue, you may need to remove other mods one by one to find the culprit. 

By the way, what's the copycats addon you have installed?

**Comment by givic** [comment]
Okay, so the problem is on the other mod's side... I will try and report back, but in the meantime here is a screenshot of the mod that was installed (actually I don't know if it can be considered an addon, but the functionality is very similar).
![image](https://github.com/user-attachments/assets/05abb9fd-2f7a-4ce5-a326-80f85da01655)

**Comment by givic** [comment]
[crash-2024-08-04_17.35.25-fml.txt](https://github.com/user-attachments/files/16487692/crash-2024-08-04_17.35.25-fml.txt)
this log without create connected and copycats.

[crash-2024-08-04_17.37.37-fml.txt](https://github.com/user-attachments/files/16487703/crash-2024-08-04_17.37.37-fml.txt)
this log is without create connected but with copycats f and also its "addon" creates сopies and cats. 

as I understand I will have to manually search for mod dependencies and write already to its developer?

**Comment by hlysine** [comment]
Yeah you need to remove your mods one by one until the crash is fixed, then the last mod you've removed is the source of the issue.

Create: Copies & Cats isn't an addon to Copycats+. You can remove that mod because the author of that mod is now part of our Copycats+ dev team and all features from that mod are now in Copycats+.

**Comment by givic** [comment]
Well, thank you for your help and explanation.

**Comment by givic** [comment]
Well, thank you for your help and explanation.
