### ISSUE TITLE
[Bug] Game Crash when looking at a structure??

### ISSUE THREAD

**Issue by DrowningDevil** [copycats-plus/copycats#149]
**Describe the bug and how to reproduce**
I can fly around wherever I want - old chunks, new chunks, underground, spectator mode - but as soon as I look at a block part of a structure it crashes my game and throws a copycat error in the crash log

the second error it throws in the log provided is create but I also have instances of it not throwing a create but a copycat and itemscollector by supermartijn642 so I assume the main offender is copycat - i have not yet tried to remove all the other mods one by one to see which one it may conflict with as it is a bunch and hope someone can make sense of the error before i do have to try that

 - Minecraft Version: 1.20.1
 - Mod Loader: Forge
 - Mod Version [2.1.2]
 
([crash-2024-08-19_16.58.24-client.txt](https://github.com/user-attachments/files/16662122/crash-2024-08-19_16.58.24-client.txt))

**Comment by hlysine** [comment]
This is caused by blocks in some other mods not having their block entities registered correctly, which leads to a crash in the copycat migration process. If you can isolate the block that causes this crash, you can report that to the mod author. We can also add a check on our end to prevent the crash, but for now, please disable migration in the Copycats+ config to work around this.
