### ISSUE TITLE
Incompatibility with Create: "Dreams & Desires"

### ISSUE THREAD

**Issue by bauerwilhelm** [copycats-plus/copycats#19]
I played around with some copycats and suddenly, vertical slab placing makes my game crash. I deactivated Copycats and started the game - no problems. I activated Copycats again and now I can't load the game at all because it crashed while loading the mods D&D is now not loadable. I do nothing but restart, now it works. I place a vertical slab, believe it or not: Crash :D 

I can provide all the last crash logs if you want them, for now I added the last one where the problem with the placing occurs.
[crash-2024-03-03_14.46.14-server.txt](https://github.com/copycats-plus/copycats/files/14473150/crash-2024-03-03_14.46.14-server.txt)

**Comment by hlysine** [comment]
This is caused by an issue in Create: Connected, not Copycats+. I've fixed it in code but haven't got the time to release it yet. See https://github.com/hlysine/create_connected/issues/48

**Comment by bauerwilhelm** [comment]
Ah got it. I have not really a clue how to read an error log but what I understood (wrong seemingly) was that the copycat+ slab couldn't find a direction or something like that :D I'm happily waiting for the update, thank you very much😇
Wouldn't it be the best way, if all modders delete the copycats in their mods so only copycats+ would add them?

**Comment by hlysine** [comment]
> Wouldn't it be the best way, if all modders delete the copycats in their mods so only copycats+ would add them?

It's actually quite the opposite. Since people have been using different mods for copycats already, deleting copycats in other mods would break all existing worlds. Ideally, all mods would keep their copycats and implement migration like Create: Connected, but this isn't a simple task, so recipe compat is the most I would reasonably expect.

Btw, if you want the fix for this crash, you can find a dev version here: https://github.com/hlysine/create_connected/issues/48#issuecomment-1951340012
