### ISSUE TITLE
Bruh, your fix is unfix.

### ISSUE THREAD

**Issue by Gintas2002** [copycats-plus/copycats#64]
Bruh, you said on fixes page - fixed tags breaking... but you literally broke it, every block cant mine with pickaxe or axe...

**Comment by Bennyboy1695** [comment]
Version info?

**Comment by LiteWolf101** [comment]
Ill add a little more info:

Minecraft Version: 1.20.1
Mod Loader: Forge - 47.3.1
Mod version: Copycats-forge.1.20.1-1.3.1

@Gintas2002 Can confirm that in this version, the block breaking is working as intended. Make sure that you have the latest update installed. If you are using the CurseForge client, you may find that you have to manually install the new update as there is a bug where CurseForge is assuming that the previous version is the latest because it probably hasn't been approved yet

**Comment by antoniomf97** [comment]
I have the same issue for version `Copycats-forge.1.20.1-1.3.0` (with Forge - 47.3.0). 
To make it playable, I had to downgrade to the version `Copycats-forge.1.20.1-1.2.6`. 
I believe the issue lies in the `is_mineable` tag, as the mod [Load My F***ing Tags](https://github.com/Dragon-Seeker/LoadMyFingTags) raises the error "is cooked".

**Comment by Bennyboy1695** [comment]
> I have the same issue for version `Copycats-forge.1.20.1-1.3.0` (with Forge - 47.3.0). To make it playable, I had to downgrade to the version `Copycats-forge.1.20.1-1.2.6`. I believe the issue lies in the `is_mineable` tag, as the mod [Load My F***ing Tags](https://github.com/Dragon-Seeker/LoadMyFingTags) raises the error "is cooked".

you need to upgrade to 1.3.1. 1.3.0 contained a block that didn't exist in the tags and broke all tags because of it. But 1.3.1 was released shortly after to fix that
